# Generated by Django 2.2.2 on 2019-08-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190810_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userid',
            field=models.CharField(db_column='User_ID', max_length=8, unique=True),
        ),
    ]
