# Generated by Django 2.2.2 on 2020-02-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('lastname', models.TextField(blank=True, db_column='LastName', null=True)),
                ('firstname', models.TextField(blank=True, db_column='FirstName', null=True)),
                ('employeenumber', models.IntegerField(blank=True, db_column='EmployeeNumber', null=True)),
                ('worksiteid', models.IntegerField(blank=True, db_column='WorkSiteID', null=True)),
                ('marriedid', models.IntegerField(blank=True, db_column='MarriedID', null=True)),
                ('maritalstatusid', models.IntegerField(blank=True, db_column='MaritalStatusID', null=True)),
                ('genderid', models.IntegerField(blank=True, db_column='GenderID', null=True)),
                ('empstatusid', models.IntegerField(blank=True, db_column='EmpStatusID', null=True)),
                ('deptid', models.IntegerField(blank=True, db_column='DeptID', null=True)),
                ('perfscoreid', models.IntegerField(blank=True, db_column='PerfScoreID', null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('payrate', models.DecimalField(blank=True, db_column='PayRate', decimal_places=2, max_digits=4, null=True)),
                ('state', models.TextField(blank=True, db_column='State', null=True)),
                ('zip', models.IntegerField(blank=True, db_column='Zip', null=True)),
                ('dob', models.DateTimeField(blank=True, db_column='DOB', null=True)),
                ('sex', models.TextField(blank=True, db_column='Sex', null=True)),
                ('maritaldesc', models.TextField(blank=True, db_column='MaritalDesc', null=True)),
                ('citizendesc', models.TextField(blank=True, db_column='CitizenDesc', null=True)),
                ('hispanic_latino', models.TextField(blank=True, db_column='Hispanic_Latino', null=True)),
                ('racedesc', models.TextField(blank=True, db_column='RaceDesc', null=True)),
                ('hiredate', models.DateTimeField(blank=True, db_column='HireDate', null=True)),
                ('terminationdate', models.TextField(blank=True, db_column='TerminationDate', null=True)),
                ('reasonforterm', models.TextField(blank=True, db_column='ReasonForTerm', null=True)),
                ('employmentstatus', models.TextField(blank=True, db_column='EmploymentStatus', null=True)),
                ('department', models.TextField(blank=True, db_column='Department', null=True)),
                ('position', models.TextField(blank=True, db_column='Position', null=True)),
                ('managername', models.TextField(blank=True, db_column='ManagerName', null=True)),
                ('employeesource', models.TextField(blank=True, db_column='EmployeeSource', null=True)),
                ('performancescore', models.TextField(blank=True, db_column='PerformanceScore', null=True)),
            ],
            options={
                'db_table': 'Employee_Data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HrCasesData',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('caseid', models.TextField(blank=True, db_column='CaseID', null=True)),
                ('requestorid', models.IntegerField(blank=True, db_column='RequestorID', null=True)),
                ('requestortype', models.TextField(blank=True, db_column='RequestorType', null=True)),
                ('caseowner', models.TextField(blank=True, db_column='CaseOwner', null=True)),
                ('casetype', models.TextField(blank=True, db_column='CaseType', null=True)),
                ('casestatus', models.TextField(blank=True, db_column='CaseStatus', null=True)),
                ('tierlevel', models.TextField(blank=True, db_column='TierLevel', null=True)),
                ('priority', models.TextField(blank=True, db_column='Priority', null=True)),
                ('datereceived', models.TextField(blank=True, db_column='DateReceived', null=True)),
                ('satisfactionscore', models.TextField(blank=True, db_column='SatisfactionScore', null=True)),
                ('dateclosed', models.TextField(blank=True, db_column='DateClosed', null=True)),
            ],
            options={
                'db_table': 'HR_Cases_Data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionStaff',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('lastname', models.TextField(blank=True, db_column='LastName', null=True)),
                ('firstname', models.TextField(blank=True, db_column='FirstName', null=True)),
                ('racedesc', models.TextField(blank=True, db_column='RaceDesc', null=True)),
                ('hiredate', models.DateTimeField(blank=True, db_column='HireDate', null=True)),
                ('termdate', models.TextField(blank=True, db_column='TermDate', null=True)),
                ('reasonforterm', models.TextField(blank=True, db_column='ReasonForTerm', null=True)),
                ('employmentstatus', models.TextField(blank=True, db_column='EmploymentStatus', null=True)),
                ('department', models.TextField(blank=True, db_column='Department', null=True)),
                ('position', models.TextField(blank=True, db_column='Position', null=True)),
                ('pay', models.TextField(blank=True, db_column='Pay', null=True)),
                ('managername', models.TextField(blank=True, db_column='ManagerName', null=True)),
                ('performancescore', models.TextField(blank=True, db_column='PerformanceScore', null=True)),
                ('abutmentsperhourwk1', models.IntegerField(blank=True, db_column='AbutmentsPerHourWk1', null=True)),
                ('abutmentsperhourwk2', models.IntegerField(blank=True, db_column='AbutmentsPerHourWk2', null=True)),
                ('dailyerrorrate', models.IntegerField(blank=True, db_column='DailyErrorRate', null=True)),
                ('complaints_90days', models.IntegerField(blank=True, db_column='Complaints_90Days', null=True)),
            ],
            options={
                'db_table': 'Production_Staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecruitingCosts2018',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('employmentsource', models.TextField(blank=True, db_column='EmploymentSource', null=True)),
                ('january_2018', models.IntegerField(blank=True, db_column='January_2018', null=True)),
                ('february_2018', models.IntegerField(blank=True, db_column='February_2018', null=True)),
                ('march_2018', models.IntegerField(blank=True, db_column='March_2018', null=True)),
                ('april_2018', models.IntegerField(blank=True, db_column='April_2018', null=True)),
                ('may_2018', models.IntegerField(blank=True, db_column='May_2018', null=True)),
                ('june_2018', models.IntegerField(blank=True, db_column='June_2018', null=True)),
                ('july_2018', models.IntegerField(blank=True, db_column='July_2018', null=True)),
                ('august_2018', models.IntegerField(blank=True, db_column='August_2018', null=True)),
                ('september_2018', models.IntegerField(blank=True, db_column='September_2018', null=True)),
                ('october_2018', models.IntegerField(blank=True, db_column='October_2018', null=True)),
                ('november_2018', models.IntegerField(blank=True, db_column='November_2018', null=True)),
                ('december_2018', models.IntegerField(blank=True, db_column='December_2018', null=True)),
            ],
            options={
                'db_table': 'Recruiting_Costs_2018',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryGrid2019',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('position', models.TextField(blank=True, db_column='Position', null=True)),
                ('salary_min', models.IntegerField(blank=True, db_column='Salary_Min', null=True)),
                ('salary_mid', models.IntegerField(blank=True, db_column='Salary_Mid', null=True)),
                ('salary_max', models.IntegerField(blank=True, db_column='Salary_Max', null=True)),
                ('hourly_min', models.DecimalField(blank=True, db_column='Hourly_Min', decimal_places=2, max_digits=4, null=True)),
                ('hourly_mid', models.DecimalField(blank=True, db_column='Hourly_Mid', decimal_places=2, max_digits=4, null=True)),
                ('hourly_max', models.DecimalField(blank=True, db_column='Hourly_Max', decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'Salary_Grid_2019',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeToFill5Yrs',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('fiscalyear', models.IntegerField(blank=True, db_column='FiscalYear', null=True)),
                ('quarter', models.TextField(blank=True, db_column='Quarter', null=True)),
                ('department', models.TextField(blank=True, db_column='Department', null=True)),
                ('processstartdate', models.DateTimeField(blank=True, db_column='ProcessStartDate', null=True)),
                ('recruitmentdate', models.DateTimeField(blank=True, db_column='RecruitmentDate', null=True)),
                ('position', models.TextField(blank=True, db_column='Position', null=True)),
                ('employeesource', models.TextField(blank=True, db_column='EmployeeSource', null=True)),
                ('totaldaysforrecruitmentcompletion', models.IntegerField(blank=True, db_column='TotalDaysForRecruitmentCompletion', null=True)),
                ('positiontypegoal', models.IntegerField(blank=True, db_column='PositionTypeGoal', null=True)),
                ('successfulrecruitment', models.IntegerField(blank=True, db_column='SuccessfulRecruitment', null=True)),
            ],
            options={
                'db_table': 'Time_To_Fill_5yrs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkSiteLocations',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('siteid', models.IntegerField(blank=True, db_column='SiteID', null=True)),
                ('sitename', models.TextField(blank=True, db_column='SiteName', null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
                ('city', models.TextField(blank=True, db_column='City', null=True)),
                ('state', models.TextField(blank=True, db_column='State', null=True)),
                ('zipcode', models.IntegerField(blank=True, db_column='ZipCode', null=True)),
                ('mainphone', models.TextField(blank=True, db_column='MainPhone', null=True)),
            ],
            options={
                'db_table': 'Work_Site_Locations',
                'managed': False,
            },
        ),
    ]
